### ISSUE TITLE
想问一下战列的面标CD指的是战列炮在仓库里的数据还是装备在舰娘身上的数据？

### ISSUE THREAD

**Issue by LostMyMind** [AzurLaneTools/AzurLaneCDTool#1]
我的153装填的约克公爵，使用大帝炮（19.42s），装备面板上的CD是16.96s左右，但是我将大帝炮在仓库中的数据与约克公爵的面板装填填入计算器中，得到的实际CD却远大于这个值，大概是19秒多。
请问一下战列的面标CD指的是战列炮在舰娘身上的数据吗？

**Comment by AutumnSun1996** [comment]
是装备在舰娘身上时的数据。
这样设计的目的是减少需要检查的界面数量，填写一个舰娘的信息只需要查看装备界面和属性界面，无需再拆下装备去仓库看CD。

**Comment by LostMyMind** [comment]
> 是装备在舰娘时的数据。 这样设计的目的是需要重新检查的界面数量，填写一个舰娘的信息只需要查看界面和属性界面，不需要再拆下装备去仓库看CD。

谢谢
