### ISSUE TITLE
目前网页不支持保存调速数据嘛

### ISSUE THREAD

**Issue by yyylq315** [AzurLaneTools/AzurLaneCDTool#12]
目前网页不支持保存数据嘛还是我的浏览器设置问题，这周调了三个队伍的cd，但是重新打开还是上一次的数据。
用的是最新版chrome浏览器

**Comment by AutumnSun1996** [comment]
目前的逻辑是在退出前自动保存数据。可以确认一下是不是这两种情况：
- 浏览器异常退出，导致数据丢失。
- 同时打开了多个页面，导致其他页面的数据被最后关闭的页面的数据覆盖。

**Comment by yyylq315** [comment]
试了一下只打开三个页面，然后关闭cd计算的标签页重新打开，可以保存。
之前是同时打开七八个页面，然后测试只关闭打开cd计算的标签页(不是关闭整个窗口)，就是无法保存。
不过问题确实是解决了，多谢
