### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Resonance1983** [AzurLaneTools/AzurLaneCDTool#15]
装备的养成曲线挺长的，所以很多装备都不太能满级特别是飞机所以希望加入一个选择装备等级的功能（现在好像只有装填弹链有类似的功能）
此外，希望能加入跨队效果，例如独立改的8%装填，不过这个貌似不是很重要，因为加装填的跨队好像就这一个

ps：这是我见过最好的调速工具，非常感谢大佬，加油

**Comment by AutumnSun1996** [comment]
谢谢你的建议。

关于装备，玩到后期就会知道啦，装备+10是没有什么难度的。而+10之后CD都不会再变，所以都没有给选择。
弹链主要是因为加的装填不一致，考虑部分调速可能会用到低等级的弹链，所以单独添加了一下。

关于跨队效果，例如独立改的8%装填，设计上是需要手动填写额外装填来配置的。
因为可能有独立改跨队、指挥猫、带有触发条件的技能等很多不同的情况影响CD，直接手动填写在实现上会方便不少，使用时的额外操作也不算非常多。
如果需求较强，并且之后时间充足的话，会考虑添加一些常见的装填Buff。
