### ISSUE TITLE
胡腾技能“致无名者的愚弄状“未模拟

### ISSUE THREAD

**Issue by vecStardo** [AzurLaneTools/AzurLaneCDTool#17]
没有正确模拟胡腾致无名者的愚弄状，处于僚舰时致无名者的愚弄状减少主炮准备时间的效果
<img width="1604" alt="截屏2024-03-03 04 44 52" src="https://github.com/AzurLaneTools/az-cd/assets/76275318/7b61905d-8f89-41df-b872-75a36a8c50c3">

**Comment by AutumnSun1996** [comment]
此类持续生效的CD减少技能可以通过手动设置射速来模拟，技能模拟主要针对作战时效果不断变化，无法手动配置的特殊技能。

例如胡腾的这个技能，将射速+配置为50%即可。
