### ISSUE TITLE
奇尔沙治等部分舰娘装填值错误

### ISSUE THREAD

**Issue by mijkl** [AzurLaneTools/AzurLaneCDTool#19]
奇爾沙治的裝填值設定出錯了，還有希望更新蘇維埃同盟活動的船和裝備
![螢幕擷取畫面 2024-03-19 070417](https://github.com/AzurLaneTools/az-cd/assets/77557595/dcbd8ee6-b34d-4256-9659-2c4fa2d31c47)
![螢幕擷取畫面 2024-03-19 070435](https://github.com/AzurLaneTools/az-cd/assets/77557595/2de3c3b6-ffb3-4a6a-b4b0-12aa6153145a)
![螢幕擷取畫面 2024-03-19 070502](https://github.com/AzurLaneTools/az-cd/assets/77557595/86dc5cbe-2248-418e-b14e-4eff4facdc33)
![image](https://github.com/AzurLaneTools/az-cd/assets/77557595/00f8074d-b14e-43f8-a388-1ca93008bc90)

**Comment by AutumnSun1996** [comment]
检查了下，是部分新的科技舰娘使用了新的装填数据来源，已经进行修复。顺便把数据也都补上了。

**Comment by mijkl** [comment]
十分感謝你更新

AutumnSun ***@***.***> 於 2024年3月24日 週日 下午9:18寫道：
