### ISSUE TITLE
飞机调速装备缺少

### ISSUE THREAD

**Issue by bayuefengbao** [AzurLaneTools/AzurLaneCDTool#20]
核心月度有个装备叫航空整备小组，希望可以添加到cd计算器里面
<img width="175" alt="{110279EA-C233-4986-AAF0-2CBC57F90EA6}" src="https://github.com/AzurLaneTools/az-cd/assets/63213015/b5719fb2-9097-42d8-9897-b047e5752adf">

**Comment by AutumnSun1996** [comment]
多谢提醒，会在近期抽空添加
