### ISSUE TITLE
预装填不能正常显示

### ISSUE THREAD

**Issue by xyf007** [AzurLaneTools/AzurLaneCDTool#29]
如图，首轮 CD 填写 大于 85 时底下模拟会消失
![image](https://github.com/user-attachments/assets/9a8ebf56-4952-46c5-b088-38c71ce5fa37)
![image](https://github.com/user-attachments/assets/8f4f7ebd-3c9b-46be-a2cb-ee3ff45e1514)

**Comment by WavinFlag** [comment]
目前在总CD减少超过100%时会出现计算问题（“电表倒转”），可以手动限制为不超过100%（含火控雷达加成）。
PR #30 合并后即可解决。
