### ISSUE TITLE
另算火箭弹命中时间

### ISSUE THREAD

**Issue by husky072399** [AzurLaneTools/AzurLaneCDTool#4]
大佬，可不可以增加火箭弹的命中时？

**Comment by AutumnSun1996** [comment]
目前可以统一修改全局的命中延迟时间和命中持续时间。
可以通过减少命中延迟时间并增加命中持续时间，让计算结果展示的命中开始时间是火箭弹的命中时间。

![image](https://user-images.githubusercontent.com/20429502/166881997-cecaff59-0601-4f52-81eb-97a370ff3f8f.png)

暂时不准备支持更复杂的机制。
