### ISSUE TITLE
支持添加前排舰娘

### ISSUE THREAD

**Issue by mijkl** [AzurLaneTools/AzurLaneCDTool#5]
能麻煩你更新添加前衛進艦娘管理欄嗎

**Comment by husky072399** [comment]
顶一下，如果作者实在是没时间可以放个说明如何添加新舰娘

**Comment by AutumnSun1996** [comment]
这个CD计算器设计时只考虑了后排
添加前排舰娘的话，会涉及主炮/副炮/魔法副炮/鱼雷的CD计算和展示方式、新增武器、技能效果确认等问题，需要修改 vue/src/components/ 和 vue/src/utils 中的相关逻辑, 工作量会比较大
我本人目前没有太多时间来进行维护，只会偶尔更新一下后排舰娘列表和后排武器列表以及bug修复, 所以暂时没有支持前排的计划

>  顶一下，如果作者实在是没时间可以放个说明如何添加新舰娘

新舰娘和武器的添加我之后加个简单的说明吧。不过由于设计上的限制, 在不改代码的情况下添加前排舰娘应该不怎么方便

**Comment by mijkl** [comment]
作者大佬你好，首先感謝你的付出

然後更正一下前衛是一只新的ur戰列艦，名字就叫前衛

再來是腓特列大帝的技能官方修復過了，目前的話模擬會和實際開砲軸不同

AutumnSun ***@***.***> 於 2022年6月27日 週一 上午10:49 寫道：

**Comment by AutumnSun1996** [comment]
数据已更新到6.2.127版本

> 再來是腓特列大帝的技能官方修復過了，目前的話模擬會和實際開砲軸不同

看技能描述没有变化. 如果确认不一致的话, 请单独开一个Issue并添加更详细的说明
