### ISSUE TITLE
關於腓特列大帝技能裝填

### ISSUE THREAD

**Issue by mijkl** [AzurLaneTools/AzurLaneCDTool#6]
如題

腓特列大帝的技能在遊戲實際測試時會與CD計算工具的結果有落差

![image](https://user-images.githubusercontent.com/77557595/176153687-a80557c8-a16f-4bc9-b9ec-bd9918844d4f.png)

https://www.youtube.com/watch?v=PGgv40F2xz8

**Comment by AutumnSun1996** [comment]
Duplicate of #2
因为腓特列大帝技能导致战列公共CD不再是预设的固定值, 进而出现模拟结果和游戏不一致的情况

如果在不涉及公共CD的情况下仍存在问题, 请提供更多信息并重新开启issue

**Comment by mijkl** [comment]
我在新的發問下有附youtube測試影片連結

https://www.youtube.com/watch?v=PGgv40F2xz8

這個影片網址

AutumnSun ***@***.***> 於 2022年6月28日 週二 下午10:25 寫道：
