### ISSUE TITLE
选择舰娘后没有出现装备信息

### ISSUE THREAD

**Issue by jveldd** [AzurLaneTools/AzurLaneCDTool#8]
网站只有空船没有装备，怎么解决？

**Comment by AutumnSun1996** [comment]
没有理解你的意思。请提供更详细的描述，比如预期行为和实际行为

**Comment by jveldd** [comment]
是这样的，我这边的网页只能加船改属性，添加装备的地方甚至没有，没有装备的话就不能看自己的时间轴，只能看海妈轴

**Comment by AutumnSun1996** [comment]
使用的浏览器是什么? 这个项目没有做浏览器适配, 建议使用Chrome浏览器, 或者新版Edge

**Comment by AutumnSun1996** [comment]
如果是说选择舰娘后没有出现装备信息的话, 是因为没有选择装备

图中'实际CD: NaN－－－－－', 这里的几个横线是装备选择区域, 可以点击这里打开装备选择界面

![image](https://user-images.githubusercontent.com/20429502/191035361-933dcf03-587d-4b35-98b4-7638f7a48fd9.png)

**Comment by jveldd** [comment]
已知晓，后续更新请提供明确提示，不然可能误认为这里生成数字
